/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GameLayoutImport } from './routes/$game/_layout'
import { Route as GameLayoutSearchWordImport } from './routes/$game/_layout/search.$word'

// Create Virtual Routes

const GameImport = createFileRoute('/$game')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const GameLayoutIndexLazyImport = createFileRoute('/$game/_layout/')()

// Create/Update Routes

const GameRoute = GameImport.update({
  path: '/$game',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GameLayoutRoute = GameLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => GameRoute,
} as any)

const GameLayoutIndexLazyRoute = GameLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => GameLayoutRoute,
} as any).lazy(() =>
  import('./routes/$game/_layout/index.lazy').then((d) => d.Route),
)

const GameLayoutSearchWordRoute = GameLayoutSearchWordImport.update({
  path: '/search/$word',
  getParentRoute: () => GameLayoutRoute,
} as any).lazy(() =>
  import('./routes/$game/_layout/search.$word.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/$game': {
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/$game/_layout': {
      preLoaderRoute: typeof GameLayoutImport
      parentRoute: typeof GameRoute
    }
    '/$game/_layout/': {
      preLoaderRoute: typeof GameLayoutIndexLazyImport
      parentRoute: typeof GameLayoutImport
    }
    '/$game/_layout/search/$word': {
      preLoaderRoute: typeof GameLayoutSearchWordImport
      parentRoute: typeof GameLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  GameRoute.addChildren([
    GameLayoutRoute.addChildren([
      GameLayoutIndexLazyRoute,
      GameLayoutSearchWordRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
